version: '3.8'

services:
  udp_sender:
    build:
      context: ./AR_UDP_Sender
    container_name: udp_sender
    networks:
      - udpnet
    restart: unless-stopped
    tty: true      # keeps container running to see logs if needed
    stdin_open: true

  udp_receiver:
    build:
      context: ./AR_UDP_Receiver
    container_name: udp_receiver
    networks:
      - udpnet
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  udpnet:
    driver: bridge